
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampaignEntriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['parent' => 'PARENT', 'campaign_name' => 'Campaigns'],
            ['parent' => 'PARENT P-CORD', 'campaign_name' => 'PARENT P-CORD PT'],
            ['parent' => 'PARENT EXTENSION', 'campaign_name' => 'PARENT EXTENSION PT'],
            ['parent' => 'SS HD CRANK', 'campaign_name' => 'SS HD CRANK'],
            ['parent' => 'PARENT DT', 'campaign_name' => 'PARENT DT'],
            ['parent' => 'PARENT DT', 'campaign_name' => 'PARENT DT HEAD'],
            ['parent' => 'PARENT CD', 'campaign_name' => 'PARENT CD'],
            ['parent' => 'PARENT CD', 'campaign_name' => 'PARENT CD PT'],
            ['parent' => 'PARENT ALLIGATOR', 'campaign_name' => 'PARENT ALLIGATOR PT'],
            ['parent' => 'PARENT KS 2X', 'campaign_name' => 'PARENT KS 2X'],
            ['parent' => 'PARENT KS 2X', 'campaign_name' => 'PARENT KS 2X PT'],
            ['parent' => 'PARENT KS 2X', 'campaign_name' => 'PARENT KS 2X HEAD'],
            ['parent' => 'PARENT MEGA PRO', 'campaign_name' => 'PARENT MEGA PRO'],
            ['parent' => 'PARENT KB Z1 COMBO', 'campaign_name' => 'PARENT KB Z1 COMBO'],
            ['parent' => 'SS HD CRANK', 'campaign_name' => 'SS HD CRANK PT'],
            ['parent' => 'PARENT MEGA PRO', 'campaign_name' => 'PARENT MEGA PRO PT'],
            ['parent' => 'PARENT HW 405', 'campaign_name' => 'PARENT HW 405'],
            ['parent' => 'PARENT HW 405', 'campaign_name' => 'PARENT HW 405 PT'],
            ['parent' => 'PARENT GRDN SPK', 'campaign_name' => 'PARENT GRDN SPK HEAD'],
            ['parent' => 'PARENT KS 1X', 'campaign_name' => 'PARENT KS 1X PT'],
            ['parent' => 'PARENT MX XU', 'campaign_name' => 'PARENT MX XU'],
            ['parent' => 'PARENT 15 FR', 'campaign_name' => 'PARENT 15 FR'],
            ['parent' => 'PARENT P-CORD', 'campaign_name' => 'PARENT P-CORD'],
            ['parent' => 'PARENT MX XU', 'campaign_name' => 'PARENT MX XU PT'],
            ['parent' => 'PARENT 12 FR', 'campaign_name' => 'PARENT 12 FR'],
            ['parent' => 'PARENT DS GT', 'campaign_name' => 'PARENT DS GT'],
            ['parent' => 'PARENT DS GT', 'campaign_name' => 'PARENT DS GT HEAD'],
            ['parent' => 'PARENT MX XU', 'campaign_name' => 'PARENT MX XU HEAD'],
            ['parent' => 'PARENT MIC 883', 'campaign_name' => 'PARENT MIC 883'],
            ['parent' => 'PARENT GHOOK', 'campaign_name' => 'PARENT GHOOK PT'],
            ['parent' => 'PARENT MSSB', 'campaign_name' => 'PARENT MSSB'],
            ['parent' => 'PARENT MSSB', 'campaign_name' => 'PARENT MSSB PT'],
            ['parent' => 'PARENT UNDR ST', 'campaign_name' => 'PARENT UNDR ST PT'],
            ['parent' => 'PARENT KS 1X', 'campaign_name' => 'PARENT KS 1X'],
            ['parent' => 'PARENT HW 508', 'campaign_name' => 'PARENT HW 508 PT'],
            ['parent' => 'PARENT HW 508', 'campaign_name' => 'PARENT HW 508'],
            ['parent' => 'PARENT CONDENSOR MIC', 'campaign_name' => 'PARENT CONDENSOR MIC'],
            ['parent' => 'PARENT CONDENSOR MIC', 'campaign_name' => 'PARENT CONDENSOR MIC PT'],
            ['parent' => 'PARENT MS DBL 1Pk', 'campaign_name' => 'PARENT MS DBL 1Pk PT'],
            ['parent' => 'PARENT SS HD 1 Pk', 'campaign_name' => 'PARENT SS HD 1 Pk'],
            ['parent' => 'PARENT KS Z1 HD', 'campaign_name' => 'PARENT KS Z1 HD'],
            ['parent' => 'PARENT SS HD 4FT', 'campaign_name' => 'PARENT SS HD 4FT'],
            ['parent' => 'PARENT SS HD 4FT', 'campaign_name' => 'PARENT SS HD 4FT PT'],
            ['parent' => 'PARENT SS HD 1 Pk', 'campaign_name' => 'PARENT SS HD 1 Pk PT'],
            ['parent' => 'PARENT MX', 'campaign_name' => 'PARENT MX'],
            ['parent' => 'PARENT MS DBL 1Pk', 'campaign_name' => 'PARENT MS DBL 1Pk'],
            ['parent' => 'PARENT MUS', 'campaign_name' => 'PARENT MUS'],
            ['parent' => 'PARENT 15 FR', 'campaign_name' => 'PARENT 15 FR PT'],
            ['parent' => 'PARENT DJ RACK', 'campaign_name' => 'PARENT DJ RACK PT'],
            ['parent' => 'PARENT KS Z1 HD', 'campaign_name' => 'PARENT KS Z1 HD PT'],
            ['parent' => 'PARENT DJ RACK', 'campaign_name' => 'PARENT DJ RACK'],
            ['parent' => 'PARENT BT MIC', 'campaign_name' => 'PARENT BT MIC'],
            ['parent' => 'PARENT RM STND', 'campaign_name' => 'PARENT RM STND PT'],
            ['parent' => 'PARENT BT MIC', 'campaign_name' => 'PARENT BT MIC PT'],
            ['parent' => 'PARENT KS Z1 HD', 'campaign_name' => 'PARENT KS Z1 HD HEAD'],
            ['parent' => 'PARENT SS HD 4FT', 'campaign_name' => 'PARENT SS HD 4FT HEAD'],
            ['parent' => 'PARENT MS DBL 1Pk', 'campaign_name' => 'PARENT MS DBL 1Pk HEAD'],
            ['parent' => 'PARENT SS HD 1 Pk', 'campaign_name' => 'PARENT SS HD 1 Pk HEAD'],
            ['parent' => 'PARENT SS ECO 1Pk', 'campaign_name' => 'PARENT SS ECO 1Pk PT'],
            ['parent' => 'PARENT SS ECO 1Pk', 'campaign_name' => 'PARENT SS ECO 1Pk'],
            ['parent' => 'PARENT MUS FLD HD ACC', 'campaign_name' => 'PARENT MUS FLD HD ACC'],
            ['parent' => 'PARENT MUS FLD HD ACC', 'campaign_name' => 'PARENT MUS FLD HD ACC HEAD'],
            ['parent' => 'PARENT MUS FLD HD ACC', 'campaign_name' => 'PARENT MUS FLD HD ACC PT'],
            ['parent' => 'PARENT MEGA 20F', 'campaign_name' => 'PARENT MEGA 20F'],
            ['parent' => 'PARENT MEGA 20F', 'campaign_name' => 'PARENT MEGA 20F PT'],
            ['parent' => 'PARENT G AMP', 'campaign_name' => 'PARENT G AMP'],
            ['parent' => 'PARENT SS ECO 1Pk', 'campaign_name' => 'PARENT SS ECO 1Pk HEAD'],
            ['parent' => 'PARENT MUS', 'campaign_name' => 'PARENT MUS PT'],
            ['parent' => 'PARENT CONGO', 'campaign_name' => 'PARENT CONGO'],
            ['parent' => 'PARENT CONGO', 'campaign_name' => 'PARENT CONGO PT'],
            ['parent' => 'PARENT Retro Mic', 'campaign_name' => 'PARENT Retro Mic'],
            ['parent' => 'PARENT G PICK', 'campaign_name' => 'PARENT G PICK'],
            ['parent' => 'PARENT MEGA SMALL', 'campaign_name' => 'PARENT MEGA SMALL'],
            ['parent' => 'PARENT GS EL', 'campaign_name' => 'PARENT GS EL'],
            ['parent' => 'PARENT TW ND', 'campaign_name' => 'PARENT TW ND'],
            ['parent' => 'PARENT GS REST', 'campaign_name' => 'PARENT GS REST PT'],
            ['parent' => 'PARENT Retro Mic', 'campaign_name' => 'PARENT Retro Mic HEAD'],
            ['parent' => 'PARENT TW ND', 'campaign_name' => 'PARENT TW ND PT'],
            ['parent' => 'PARENT DS 01', 'campaign_name' => 'PARENT DS 01'],
            ['parent' => 'PARENT Retro Mic', 'campaign_name' => 'PARENT Retro Mic PT'],
            ['parent' => 'PARENT MEGA SMALL', 'campaign_name' => 'PARENT MEGA SMALL PT'],
            ['parent' => 'PARENT MIC ADP', 'campaign_name' => 'PARENT MIC ADP'],
            ['parent' => 'PARENT DRUM MIC RND', 'campaign_name' => 'PARENT DRUM MIC RND'],
            ['parent' => 'PARENT DRUM MIC RND', 'campaign_name' => 'PARENT DRUM MIC RND PT'],
            ['parent' => 'PARENT DRUM MIC RND', 'campaign_name' => 'PARENT DRUM MIC RND HEAD'],
            ['parent' => 'PARENT MIC CLIP', 'campaign_name' => 'PARENT MIC CLIP PT'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'FOG 2500'],
            ['parent' => 'PARENT GS EL', 'campaign_name' => 'PARENT GS EL PT'],
            ['parent' => 'PARENT KS Z1', 'campaign_name' => 'PARENT KS Z1 HEAD'],
            ['parent' => 'PARENT KS C 2TD', 'campaign_name' => 'PARENT KS C 2TD PT'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'FOG 1200'],
            ['parent' => 'PARENT PNB WD', 'campaign_name' => 'PARENT PNB WD'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'FOG 1200 PT'],
            ['parent' => 'PARENT MUS FLD', 'campaign_name' => 'PARENT MUS FLD PT'],
            ['parent' => 'PARENT KS C 2TD', 'campaign_name' => 'PARENT KS C 2TD HEAD'],
            ['parent' => 'PARENT MX', 'campaign_name' => 'PARENT MX PT'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'FOG 2500 PT'],
            ['parent' => 'PARENT INSTRU MIC', 'campaign_name' => 'PARENT INSTRU MIC'],
            ['parent' => 'PARENT INSTRU MIC', 'campaign_name' => 'PARENT INSTRU MIC PT'],
            ['parent' => 'PARENT GS REST', 'campaign_name' => 'PARENT GS REST'],
            ['parent' => 'PARENT RL1', 'campaign_name' => 'PARENT RL1'],
            ['parent' => 'PARENT RL1', 'campaign_name' => 'PARENT RL1 PT'],
            ['parent' => 'PARENT GRDN SPK', 'campaign_name' => 'PARENT GRDN SPK PT'],
            ['parent' => 'PARENT INSTRU MIC', 'campaign_name' => 'PARENT INSTRU MIC HEAD'],
            ['parent' => 'PARENT PNB B-REST', 'campaign_name' => 'PARENT PNB B-REST'],
            ['parent' => 'PARENT DS CH', 'campaign_name' => 'PARENT DS CH'],
            ['parent' => 'PARENT PNB B-REST', 'campaign_name' => 'PARENT PNB B-REST PT'],
            ['parent' => 'PARENT SNARE', 'campaign_name' => 'PARENT SNARE'],
            ['parent' => 'PARENT HORN', 'campaign_name' => 'PARENT HORN'],
            ['parent' => 'PARENT RM SET', 'campaign_name' => 'PARENT RM SET PT'],
            ['parent' => 'PARENT RM SET', 'campaign_name' => 'PARENT RM SET'],
            ['parent' => 'PARENT DS CH', 'campaign_name' => 'PARENT DS CH PT'],
            ['parent' => 'PARENT PNB B-REST', 'campaign_name' => 'PARENT PNB B-REST HEAD'],
            ['parent' => 'PARENT RM SET', 'campaign_name' => 'PARENT RM SET HEAD'],
            ['parent' => 'PARENT 12 WF', 'campaign_name' => 'PARENT 12 WF'],
            ['parent' => 'PARENT KBB HD', 'campaign_name' => 'PARENT KBB HD PT'],
            ['parent' => 'PARENT HOME DJ', 'campaign_name' => 'PARENT HOME DJ PT'],
            ['parent' => 'PARENT MS DBL S', 'campaign_name' => 'PARENT MS DBL S'],
            ['parent' => 'PARENT KBB HD', 'campaign_name' => 'PARENT KBB HD'],
            ['parent' => 'PARENT HOME DJ', 'campaign_name' => 'PARENT HOME DJ'],
            ['parent' => 'PARENT SPEAKON', 'campaign_name' => 'PARENT SPEAKON PT'],
            ['parent' => 'PARENT DS PR', 'campaign_name' => 'PARENT DS PR'],
            ['parent' => 'PARENT GSH', 'campaign_name' => 'PARENT GSH PT'],
            ['parent' => 'PARENT DS SDL', 'campaign_name' => 'PARENT DS SDL'],
            ['parent' => 'PARENT DS PR', 'campaign_name' => 'PARENT DS PR PT'],
            ['parent' => 'PARENT DS SDL', 'campaign_name' => 'PARENT DS SDL PT'],
            ['parent' => 'PARENT GSH', 'campaign_name' => 'PARENT GSH'],
            ['parent' => 'PARENT DS SDL', 'campaign_name' => 'PARENT DS SDL HEAD'],
            ['parent' => 'PARENT GSS', 'campaign_name' => 'PARENT GSS'],
            ['parent' => 'PARENT MS 080 1Pk', 'campaign_name' => 'PARENT MS 080 1Pk PT'],
            ['parent' => 'PARENT WALL SPK', 'campaign_name' => 'PARENT WALL SPK MTL'],
            ['parent' => 'PARENT GS EL NK', 'campaign_name' => 'PARENT GS EL NK PT'],
            ['parent' => 'PARENT MEGAPHONE', 'campaign_name' => '148 LED'],
            ['parent' => 'PARENT GSS 2N1', 'campaign_name' => 'PARENT GSS 2N1 PT'],
            ['parent' => 'PARENT PNB WD', 'campaign_name' => 'PARENT PNB WD PT'],
            ['parent' => 'PARENT GRACK', 'campaign_name' => 'PARENT GRACK'],
            ['parent' => 'PARENT GSS 2N1', 'campaign_name' => 'PARENT GSS 2N1'],
            ['parent' => 'PARENT GSH HD', 'campaign_name' => 'PARENT GSH HD PT'],
            ['parent' => 'PARENT MS 080 1Pk', 'campaign_name' => 'PARENT MS 080 1Pk'],
            ['parent' => 'PARENT MEGAPHONE', 'campaign_name' => '148 LED PT'],
            ['parent' => 'PARENT WALL SPK', 'campaign_name' => 'PARENT WALL SPK MTL PT'],
            ['parent' => 'PARENT CAR SPEAKER 69', 'campaign_name' => 'PARENT CAR SPEAKER 69'],
            ['parent' => 'PARENT SS HD 3FT', 'campaign_name' => 'PARENT SS HD 3FT PT'],
            ['parent' => 'PARENT MIC ADP', 'campaign_name' => 'PARENT MIC ADP PT'],
            ['parent' => 'PARENT GRDN SPK MC', 'campaign_name' => 'PARENT GRDN SPK MC'],
            ['parent' => 'PARENT GRDN SPK MC', 'campaign_name' => 'PARENT GRDN SPK MC PT'],
            ['parent' => 'PARENT G AMP', 'campaign_name' => 'PARENT G AMP PT'],
            ['parent' => 'PARENT CAR SPEAKER', 'campaign_name' => 'PARENT CAR SPEAKER PT'],
            ['parent' => 'PARENT CAR SPEAKER', 'campaign_name' => 'PARENT CAR SPEAKER'],
            ['parent' => 'PARENT TBMS', 'campaign_name' => 'PARENT Telescopic Mic St'],
            ['parent' => 'PARENT GRACK', 'campaign_name' => 'PARENT GRACK PT'],
            ['parent' => 'PARENT KB 2X COMBO', 'campaign_name' => 'PARENT KB 2X COMBO PT'],
            ['parent' => 'PARENT GSS 2N1', 'campaign_name' => 'PARENT GSS 2N1 HEAD'],
            ['parent' => 'PARENT FOOT REST', 'campaign_name' => 'PARENT FOOT REST PT'],
            ['parent' => 'PARENT MS DBL S', 'campaign_name' => 'PARENT MS DBL S PT'],
            ['parent' => 'PARENT FOOT REST', 'campaign_name' => 'PARENT FOOT REST'],
            ['parent' => 'PARENT GRACK', 'campaign_name' => 'PARENT GRACK HEAD'],
            ['parent' => 'PARENT MS 080 1Pk', 'campaign_name' => 'PARENT MS 080 1Pk HEAD'],
            ['parent' => 'PARENT PLASTIC MIC', 'campaign_name' => 'PARENT PLASTIC MIC'],
            ['parent' => 'PARENT MEGA KIDS', 'campaign_name' => 'PARENT MEGA KIDS'],
            ['parent' => 'PARENT MS RBP', 'campaign_name' => 'PARENT MS RBP'],
            ['parent' => 'PARENT GS EL NK', 'campaign_name' => 'PARENT GS EL NK'],
            ['parent' => 'PARENT MS RBP', 'campaign_name' => 'PARENT MS RBP PT'],
            ['parent' => 'PARENT KS Z1 HD 2T', 'campaign_name' => 'PARENT KS Z1 HD 2T'],
            ['parent' => 'PARENT KB Z1 COMBO', 'campaign_name' => 'PARENT KB Z1 COMBO PT'],
            ['parent' => 'PARENT GSTOOL', 'campaign_name' => 'PARENT GSTOOL'],
            ['parent' => 'PARENT MS RBP', 'campaign_name' => 'PARENT MS RBP HEAD'],
            ['parent' => 'PARENT MIC COPPER', 'campaign_name' => 'PARENT MIC COPPER PT'],
            ['parent' => 'PARENT MIC COPPER', 'campaign_name' => 'PARENT MIC COPPER'],
            ['parent' => 'PARENT KBB H-ADJ', 'campaign_name' => 'PARENT KBB H-ADJ'],
            ['parent' => 'PARENT XLR', 'campaign_name' => 'PARENT XLR PT'],
            ['parent' => 'PARENT MX-L', 'campaign_name' => 'PARENT MX-L PT'],
            ['parent' => 'PARENT GS EL BSS 6', 'campaign_name' => 'PARENT GS EL BSS 6'],
            ['parent' => 'PARENT KBB H-ADJ', 'campaign_name' => 'PARENT KBB H-ADJ PT'],
            ['parent' => 'PARENT KS Z1 WHL', 'campaign_name' => 'PARENT KS Z1 WHL PT'],
            ['parent' => 'PARENT KS Z1 WHL', 'campaign_name' => 'PARENT KS Z1 WHL HEAD'],
            ['parent' => 'PARENT GS EL BSS 4', 'campaign_name' => 'PARENT GS EL BSS 4'],
            ['parent' => 'PARENT XLR', 'campaign_name' => 'PARENT XLR'],
            ['parent' => 'PARENT KB 2X COMBO', 'campaign_name' => 'PARENT KB 2X COMBO'],
            ['parent' => 'PARENT TOM', 'campaign_name' => 'PARENT TOM'],
            ['parent' => 'PARENT DS BLKCH', 'campaign_name' => 'PARENT DS BLKCH'],
            ['parent' => 'PARENT TOM', 'campaign_name' => 'PARENT TOM PT'],
            ['parent' => 'PARENT MS ARM', 'campaign_name' => 'PARENT MS ARM PT'],
            ['parent' => 'PARENT TOM', 'campaign_name' => 'PARENT TOM HEAD'],
            ['parent' => 'PARENT GS EL BSS 4', 'campaign_name' => 'PARENT GS EL BSS 4 PT'],
            ['parent' => 'PARENT SS HD 2 Pk', 'campaign_name' => 'PARENT SS HD 2 Pk HEAD'],
            ['parent' => 'PARENT PA HORN', 'campaign_name' => 'PARENT PA HORN'],
            ['parent' => 'PARENT 12 FR', 'campaign_name' => 'PARENT 12 FR PT'],
            ['parent' => 'PARENT PA HORN', 'campaign_name' => 'PARENT PA HORN PT'],
            ['parent' => 'PARENT PA HORN', 'campaign_name' => 'PARENT PA HORN HEAD'],
            ['parent' => 'PARENT M-HOLDER', 'campaign_name' => 'PARENT M-HOLDER'],
            ['parent' => 'PARENT KBB SLIM', 'campaign_name' => 'PARENT KBB SLIM PT'],
            ['parent' => 'PARENT KB 1X COMBO', 'campaign_name' => 'PARENT KB 1X COMBO'],
            ['parent' => 'PARENT MS RBL', 'campaign_name' => 'PARENT MS RBL PT'],
            ['parent' => 'PARENT ALLIGATOR', 'campaign_name' => 'PARENT ALLIGATOR'],
            ['parent' => 'PARENT GS EL BSS 6', 'campaign_name' => 'PARENT GS EL BSS 6 PT'],
            ['parent' => 'PARENT KBB SLIM', 'campaign_name' => 'PARENT KBB Slim'],
            ['parent' => 'PARENT KS Z1 WHL', 'campaign_name' => 'PARENT KS Z1 WHL DISP'],
            ['parent' => 'PARENT MS RBL HND', 'campaign_name' => 'PARENT MS RBL HND'],
            ['parent' => 'PARENT SS HD 3FT', 'campaign_name' => 'PARENT SS HD 3FT'],
            ['parent' => 'PARENT Driver Unit', 'campaign_name' => 'PARENT Driver Unit PT'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'FOG 1500'],
            ['parent' => 'PARENT Driver Unit', 'campaign_name' => 'PARENT Driver Unit'],
            ['parent' => 'PARENT SPEAKON', 'campaign_name' => 'PARENT SPEAKON'],
            ['parent' => 'PARENT MUS 4S', 'campaign_name' => 'PARENT MUS 4S'],
            ['parent' => 'PARENT EXTENSION', 'campaign_name' => 'PARENT EXTENSION'],
            ['parent' => 'PARENT MX-L', 'campaign_name' => 'PARENT MX-L'],
            ['parent' => 'PARENT WF 672 PP', 'campaign_name' => 'PARENT WF 672 PP PT'],
            ['parent' => 'PARENT SS HD LGT', 'campaign_name' => 'PARENT SS HD LGT PT'],
            ['parent' => 'PARENT 5C421', 'campaign_name' => 'PARENT 5C421'],
            ['parent' => 'PARENT MUS 4S', 'campaign_name' => 'PARENT MUS 4S PT'],
            ['parent' => 'PARENT MUS 4S', 'campaign_name' => 'PARENT MUS 4S HEAD'],
            ['parent' => 'PARENT DS CH COMBO', 'campaign_name' => 'PARENT DS CH COMBO'],
            ['parent' => 'PARENT MIC CLIP', 'campaign_name' => 'PARENT MIC CLIP'],
            ['parent' => 'PARENT RM STND', 'campaign_name' => 'PARENT RM STND'],
            ['parent' => 'PARENT MX 4CH', 'campaign_name' => 'PARENT MX 4CH'],
            ['parent' => 'PARENT WM UHF 02', 'campaign_name' => 'PARENT WM UHF 02'],
            ['parent' => 'PARENT SS HD LGT', 'campaign_name' => 'PARENT SS HD LGT'],
            ['parent' => 'PARENT WM UHF 02', 'campaign_name' => 'PARENT WM UHF 02 PT'],
            ['parent' => 'PARENT DPAD', 'campaign_name' => 'PARENT DPAD PT'],
            ['parent' => 'PARENT DS REST LVR', 'campaign_name' => 'PARENT DS REST LVR'],
            ['parent' => 'PARENT DS REST LVR', 'campaign_name' => 'PARENT DS REST LVR PT'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'FOG 1500 PT'],
            ['parent' => 'PARENT DPAD', 'campaign_name' => 'PARENT DPAD'],
            ['parent' => 'PARENT TABLA MIC', 'campaign_name' => 'PARENT TABLA MIC PT'],
            ['parent' => 'PARENT 15 WF', 'campaign_name' => 'PARENT 15 WF'],
            ['parent' => 'PARENT 15 WF', 'campaign_name' => 'PARENT 15 WF PT'],
            ['parent' => 'PARENT 18 FR', 'campaign_name' => 'PARENT 18 FR'],
            ['parent' => 'PARENT 18 FR', 'campaign_name' => 'PARENT 18 FR PT'],
            ['parent' => 'PARENT DRUM MIC 7', 'campaign_name' => 'PARENT DRUM MIC 7'],
            ['parent' => 'PARENT DRUM MIC 7', 'campaign_name' => 'PARENT DRUM MIC 7 PT'],
            ['parent' => 'PARENT DS BLKCH', 'campaign_name' => 'PARENT DS BLKCH PT'],
            ['parent' => 'PARENT TABLA MIC', 'campaign_name' => 'PARENT TABLA MIC'],
            ['parent' => 'PARENT TABLA MIC', 'campaign_name' => 'PARENT TABLA MIC HEAD'],
            ['parent' => 'PARENT CAR BASS', 'campaign_name' => 'PARENT CAR BASS'],
            ['parent' => 'PARENT CAR BASS', 'campaign_name' => 'PARENT CAR BASS PT'],
            ['parent' => 'PARENT DS BLKCH', 'campaign_name' => 'PARENT DS BLKCH HEAD'],
            ['parent' => 'PARENT PLASTIC MIC', 'campaign_name' => 'PARENT PLASTIC MIC PT'],
            ['parent' => 'PARENT PLASTIC MIC', 'campaign_name' => 'PARENT PLASTIC MIC HEAD'],
            ['parent' => 'PARENT MR 8', 'campaign_name' => 'PARENT MR 8 PT'],
            ['parent' => 'PARENT CLR MIC', 'campaign_name' => 'PARENT CLR MIC'],
            ['parent' => 'PARENT CLR MIC', 'campaign_name' => 'PARENT CLR MIC PT'],
            ['parent' => 'PARENT MR 8', 'campaign_name' => 'PARENT MR 8'],
            ['parent' => 'PARENT MIC 286', 'campaign_name' => 'PARENT MIC 286 PT'],
            ['parent' => 'PARENT DP', 'campaign_name' => 'PARENT DP'],
            ['parent' => 'PARENT DP', 'campaign_name' => 'PARENT DP PT'],
            ['parent' => 'PARENT M-HOLDER', 'campaign_name' => 'PARENT M-HOLDER PT'],
            ['parent' => 'PARENT ET', 'campaign_name' => 'PARENT ET'],
            ['parent' => 'PARENT ET', 'campaign_name' => 'PARENT ET PT'],
            ['parent' => 'PARENT G PICK', 'campaign_name' => 'PARENT G PICK PT'],
            ['parent' => 'PARENT G-WINDER', 'campaign_name' => 'PARENT G-WINDER'],
            ['parent' => 'PARENT G-WINDER', 'campaign_name' => 'PARENT G-WINDER PT'],
            ['parent' => 'PARENT MS RBL', 'campaign_name' => 'PARENT MS RBL'],
            ['parent' => 'PARENT DS REST', 'campaign_name' => 'PARENT DS REST PT'],
            ['parent' => 'PARENT GS EL BSS 5', 'campaign_name' => 'PARENT GS EL BSS 5'],
            ['parent' => 'PARENT GS EL BSS 5', 'campaign_name' => 'PARENT GS EL BSS 5 PT'],
            ['parent' => 'PARENT GSS AL', 'campaign_name' => 'PARENT GSS AL'],
            ['parent' => 'PARENT GSS AL', 'campaign_name' => 'PARENT GSS AL PT'],
            ['parent' => 'PARENT GSS UKU', 'campaign_name' => 'PARENT GSS UKU PT'],
            ['parent' => 'PARENT HISE', 'campaign_name' => 'PARENT HISE'],
            ['parent' => 'PARENT HISE', 'campaign_name' => 'PARENT HISE PT'],
            ['parent' => 'PARENT M-CHARGER', 'campaign_name' => 'PARENT M-CHARGER'],
            ['parent' => 'PARENT M-CHARGER', 'campaign_name' => 'PARENT M-CHARGER PT'],
            ['parent' => 'PARENT MEGA 20R', 'campaign_name' => 'PARENT MEGA 20R'],
            ['parent' => 'PARENT MEGA 20R', 'campaign_name' => 'PARENT MEGA 20R PT'],
            ['parent' => 'PARENT MEGA 66SF', 'campaign_name' => 'PARENT MEGA 66SF'],
            ['parent' => 'PARENT MEGA 66SF', 'campaign_name' => 'PARENT MEGA 66SF PT'],
            ['parent' => 'PARENT MEGA 77SF', 'campaign_name' => 'PARENT MEGA 77SF'],
            ['parent' => 'PARENT GSH HD', 'campaign_name' => 'PARENT GSH HD'],
            ['parent' => 'PARENT MIC 286', 'campaign_name' => 'PARENT MIC 286'],
            ['parent' => 'PARENT MIC 260', 'campaign_name' => 'PARENT MIC 260'],
            ['parent' => 'PARENT MIC 260', 'campaign_name' => 'PARENT MIC 260 PT'],
            ['parent' => 'PARENT MP', 'campaign_name' => 'PARENT MP'],
            ['parent' => 'PARENT MP', 'campaign_name' => 'PARENT MP PT'],
            ['parent' => 'PARENT MR 6.5', 'campaign_name' => 'PARENT MR 6.5'],
            ['parent' => 'PARENT MR 6.5', 'campaign_name' => 'PARENT MR 6.5 PT'],
            ['parent' => 'PARENT MX 4CH 2MIC', 'campaign_name' => 'PARENT MX 4CH 2MIC'],
            ['parent' => 'PARENT MX 4CH 2MIC', 'campaign_name' => 'PARENT MX 4CH 2MIC PT'],
            ['parent' => 'PARENT MS RBL HND', 'campaign_name' => 'PARENT MS RBL HND PT'],
            ['parent' => 'PARENT PNB', 'campaign_name' => 'PARENT PNB'],
            ['parent' => 'PARENT GSTOOL', 'campaign_name' => 'PARENT GSTOOL DISP'],
            ['parent' => 'PARENT POP', 'campaign_name' => 'PARENT POP'],
            ['parent' => 'PARENT POP', 'campaign_name' => 'PARENT POP PT'],
            ['parent' => 'PARENT PS', 'campaign_name' => 'PARENT PS'],
            ['parent' => 'PARENT PS', 'campaign_name' => 'PARENT PS PT'],
            ['parent' => 'PARENT RBS BOOM', 'campaign_name' => 'PARENT RBS BOOM'],
            ['parent' => 'PARENT RBS BOOM', 'campaign_name' => 'PARENT RBS BOOM PT'],
            ['parent' => 'PARENT DS REST', 'campaign_name' => 'PARENT DS REST'],
            ['parent' => 'PARENT GSH HD', 'campaign_name' => 'PARENT GSH HD HEAD'],
            ['parent' => 'PARENT SPONGE', 'campaign_name' => 'PARENT SPONGE'],
            ['parent' => 'PARENT SPONGE', 'campaign_name' => 'PARENT SPONGE PT'],
            ['parent' => 'PARENT SS TRI BASE', 'campaign_name' => 'PARENT SS TRI BASE'],
            ['parent' => 'PARENT SS TRI BASE', 'campaign_name' => 'PARENT SS TRI BASE PT'],
            ['parent' => 'PARENT SSHD HYD', 'campaign_name' => 'PARENT SSHD HYD'],
            ['parent' => 'PARENT SSHD HYD', 'campaign_name' => 'PARENT SSHD HYD PT'],
            ['parent' => 'PARENT STRING UK', 'campaign_name' => 'PARENT STRING UK'],
            ['parent' => 'PARENT STRING UK', 'campaign_name' => 'PARENT STRING UK PT'],
            ['parent' => 'PARENT FOG', 'campaign_name' => 'PARENT FOG DISP'],
            ['parent' => 'PARENT TW 303', 'campaign_name' => 'PARENT TW 303'],
            ['parent' => 'PARENT TW 303', 'campaign_name' => 'PARENT TW 303 PT'],
            ['parent' => 'PARENT TW BLT 150', 'campaign_name' => 'PARENT TW BLT 150'],
            ['parent' => 'PARENT TW BLT 150', 'campaign_name' => 'PARENT TW BLT 150 PT'],
            ['parent' => 'PARENT TW BLT 180', 'campaign_name' => 'PARENT TW BLT 180'],
            ['parent' => 'PARENT WALL SPK', 'campaign_name' => 'PARENT WALL SPK'],
            ['parent' => 'PARENT DESK MIC STAND', 'campaign_name' => 'PARENT DESK MIC STAND'],
            ['parent' => 'PARENT WF 672 PP', 'campaign_name' => 'PARENT WF 672 PP'],
            ['parent' => 'PARENT DESK MIC STAND', 'campaign_name' => 'PARENT DESK MIC STAND PT'],
            ['parent' => 'PARENT GSS', 'campaign_name' => 'PARENT GSS PT'],
            ['parent' => 'PARENT WF 890', 'campaign_name' => 'PARENT WF 890'],
            ['parent' => 'PARENT WF 890 DBL', 'campaign_name' => 'PARENT WF 890 DBL'],
            ['parent' => 'PARENT WF 890', 'campaign_name' => 'PARENT WF 890 PT'],
            ['parent' => 'PARENT WM', 'campaign_name' => 'PARENT WM'],
            ['parent' => 'PARENT WST 01', 'campaign_name' => 'PARENT WST 01'],
            ['parent' => 'PARENT WST 02', 'campaign_name' => 'PARENT WST 02'],
            ['parent' => 'PARENT GSS', 'campaign_name' => 'PARENT GSS HEAD'],
            ['parent' => 'PARENT KBB SLIM', 'campaign_name' => 'PARENT KBB SLIM HEAD'],
            ['parent' => 'PARENT DESK MIC STAND', 'campaign_name' => 'PARENT DESK MIC STAND HEAD'],
            ['parent' => 'PARENT SNARE', 'campaign_name' => 'PARENT SNARE PT'],
            ['parent' => 'PARENT DS CH', 'campaign_name' => 'PARENT DS CH HEAD'],
            ['parent' => 'PARENT A-54', 'campaign_name' => 'PARENT A-54'],
            ['parent' => 'PARENT GRDN SPK', 'campaign_name' => 'PARENT GRDN SPK'],
            ['parent' => 'PARENT MUS FLD', 'campaign_name' => 'PARENT MUS FLD'],
            ['parent' => 'PARENT MUS FLD', 'campaign_name' => 'PARENT MUS FLD HEAD'],
            ['parent' => 'PARENT KS C 2TD', 'campaign_name' => 'PARENT KS C 2TD'],
            ['parent' => 'PARENT 5C422', 'campaign_name' => 'PARENT 5C421 PT'],
            ['parent' => 'PARENT WST 02', 'campaign_name' => 'PARENT WST 02 PT'],
            ['parent' => 'PARENT MEGA SMALL', 'campaign_name' => 'PARENT MEGA SMALL HEAD'],
            ['parent' => 'PARENT KS Z1', 'campaign_name' => 'PARENT KS Z1 PT'],
            ['parent' => 'PARENT KS Z1', 'campaign_name' => 'PARENT KS Z1'],
            ['parent' => 'PARENT DRUM MIC 7', 'campaign_name' => 'PARENT DRUM MIC 7 DISP'],
            ['parent' => 'PARENT DESK MIC STAND', 'campaign_name' => 'PARENT DESK MIC STAND DISP'],
            ['parent' => 'PARENT DS BLKCH', 'campaign_name' => 'PARENT DS BLKCH DISP'],
            ['parent' => 'PARENT CONGO', 'campaign_name' => 'PARENT CONGO DISP'],
            ['parent' => 'PARENT DRUM MIC RND', 'campaign_name' => 'PARENT DRUM MIC RND DISP'],
            ['parent' => 'PARENT DS SDL', 'campaign_name' => 'PARENT DS SDL DISP'],
            ['parent' => 'PARENT DS PR', 'campaign_name' => 'PARENT DS PR DISP'],
            ['parent' => 'PARENT DJ RACK', 'campaign_name' => 'PARENT DJ RACK DISP'],
            ['parent' => 'PARENT SS HD 4FT', 'campaign_name' => 'PARENT SS HD 4FT DISP'],
            ['parent' => 'PARENT PNB B-REST', 'campaign_name' => 'PARENT PNB B-REST DISP'],
            ['parent' => 'PARENT MUS FLD HD ACC', 'campaign_name' => 'PARENT MUS FLD HD ACC DISP'],
            ['parent' => 'PARENT GSH', 'campaign_name' => 'PARENT GSH DISP'],
            ['parent' => 'PARENT DS GT', 'campaign_name' => 'PARENT DS GT DISP'],
            ['parent' => 'PARENT DS REST', 'campaign_name' => 'PARENT DS REST DISP'],
            ['parent' => 'PARENT GRDN SPK', 'campaign_name' => 'PARENT GRDN SPK DISP'],
            ['parent' => 'PARENT HW 405', 'campaign_name' => 'PARENT HW 405 DISP'],
            ['parent' => 'PARENT SS HD 1 Pk', 'campaign_name' => 'PARENT SS HD 1 Pk DISP'],
            ['parent' => 'PARENT PNB WD', 'campaign_name' => 'PARENT PNB WD DISP'],
            ['parent' => 'PARENT SS HD LGT', 'campaign_name' => 'PARENT SS HD LGT DISP'],
            ['parent' => 'PARENT HW 508', 'campaign_name' => 'PARENT HW 508 DISP'],
            ['parent' => 'PARENT GRACK', 'campaign_name' => 'PARENT GRACK DISP'],
            ['parent' => 'PARENT DPAD', 'campaign_name' => 'PARENT DPAD DISP'],
            ['parent' => 'PARENT TABLA MIC', 'campaign_name' => 'PARENT TABLA MIC DISP'],
            ['parent' => 'PARENT SS HD 3FT', 'campaign_name' => 'PARENT SS HD 3FT DISP'],
            ['parent' => 'PARENT KS 1X', 'campaign_name' => 'PARENT KS 1X DISP'],
            ['parent' => 'PARENT SS ECO 1Pk', 'campaign_name' => 'PARENT SS ECO 1Pk DISP'],
            ['parent' => 'PARENT MS RBL', 'campaign_name' => 'PARENT MS RBL DISP'],
            ['parent' => 'PARENT DT', 'campaign_name' => 'PARENT DT DISP'],
            ['parent' => 'PARENT KS Z1', 'campaign_name' => 'PARENT KS Z1 DISP'],
            ['parent' => 'PARENT MUS 4S', 'campaign_name' => 'PARENT MUS 4S DISP'],
            ['parent' => 'PARENT GSS 2N1', 'campaign_name' => 'PARENT GSS 2N1 DISP'],
            ['parent' => 'PARENT MS DBL 1Pk', 'campaign_name' => 'PARENT MS DBL 1Pk DISP'],
            ['parent' => 'PARENT KS C 2TD', 'campaign_name' => 'PARENT KS C 2TD DISP'],
            ['parent' => 'PARENT GSS', 'campaign_name' => 'PARENT GSS DISP'],
            ['parent' => 'PARENT PARTY SPK', 'campaign_name' => 'PARENT PARTY SPK DISP'],
            ['parent' => 'PARENT KBB SLIM', 'campaign_name' => 'PARENT KBB SLIM DISP'],
            ['parent' => 'PARENT KBB H-ADJ', 'campaign_name' => 'PARENT KBB H-ADJ DISP'],
            ['parent' => 'PARENT MSSB', 'campaign_name' => 'PARENT MSSB DISP'],
            ['parent' => 'PARENT MEGA 77SF', 'campaign_name' => 'PARENT MEGA 77SF PT'],
            ['parent' => 'PARENT GSTOOL', 'campaign_name' => 'PARENT GSTOOL PT'],
            ['parent' => 'PARENT WM', 'campaign_name' => 'PARENT WM PT'],
            ['parent' => 'PARENT DS 01', 'campaign_name' => 'PARENT DS 01 PT'],
            ['parent' => 'PARENT SS HD 2 Pk', 'campaign_name' => 'PARENT SS HD 2 Pk PT'],
            ['parent' => 'PARENT SS HD 2 Pk', 'campaign_name' => 'PARENT SS HD 2 Pk'],
            ['parent' => 'PARENT DS 01', 'campaign_name' => 'PARENT DS 01 HEAD'],
            ['parent' => 'PARENT MEGA 20F', 'campaign_name' => 'PARENT MEGA 20F HEAD'],
            ['parent' => 'PARENT MR 8', 'campaign_name' => 'PARENT MR 8 HEAD'],
            ['parent' => 'PARENT MUS MH', 'campaign_name' => 'PARENT MUS MH'],
            ['parent' => 'PARENT ARM SET', 'campaign_name' => 'PARENT ARM SET'],
            ['parent' => 'PARENT ARM SET', 'campaign_name' => 'PARENT ARM SET PT'],
            ['parent' => 'PARENT MUS MH', 'campaign_name' => 'PARENT MUS MH PT'],
            ['parent' => 'PARENT ND-58', 'campaign_name' => 'PARENT ND-58'],
            ['parent' => 'PARENT ND-58', 'campaign_name' => 'PARENT ND-58 PT'],
            ['parent' => 'PARENT Retro Mic', 'campaign_name' => 'PARENT Retro Mic DISP'],
            ['parent' => 'PARENT KS 2X', 'campaign_name' => 'PARENT KS 2X DISP'],
            ['parent' => 'PARENT KS Z1 HD', 'campaign_name' => 'PARENT KS Z1 HD DISP'],
            ['parent' => 'PARENT MUS FLD', 'campaign_name' => 'PARENT MUS FLD DISP'],
            ['parent' => 'PARENT GSH HD', 'campaign_name' => 'PARENT GSH HD DISP'],
            ['parent' => 'PARENT MS RBP', 'campaign_name' => 'PARENT MS RBP DISP'],
            ['parent' => 'PARENT TOM', 'campaign_name' => 'PARENT TOM DISP'],
            ['parent' => 'PARENT WM UHF HM', 'campaign_name' => 'PARENT WM UHF HM'],
            ['parent' => 'PARENT WM UHF HM', 'campaign_name' => 'PARENT WM UHF HM PT'],
            ['parent' => 'PARENT DS VEL', 'campaign_name' => 'PARENT DS VEL'],
            ['parent' => 'PARENT DS VEL', 'campaign_name' => 'PARENT DS VEL PT'],
            ['parent' => 'PARENT ND MIC', 'campaign_name' => 'PARENT ND MIC PT'],
            ['parent' => 'PARENT ND MIC', 'campaign_name' => 'PARENT ND MIC'],
            ['parent' => 'PARENT ND MIC', 'campaign_name' => 'PARENT ND MIC HEAD'],
            ['parent' => 'PARENT KS 1X', 'campaign_name' => 'PARENT KS 1X HEAD'],
            ['parent' => 'PARENT UNDR ST', 'campaign_name' => 'PARENT UNDR ST'],
            ['parent' => 'PARENT GHOOK', 'campaign_name' => 'PARENT GHOOK'],
            ['parent' => 'PARENT KS Z1 WHL', 'campaign_name' => 'PARENT KS Z1 WHL'],
            ['parent' => 'PARENT MIC 883', 'campaign_name' => 'PARENT MIC 883 PT'],
            ['parent' => 'PARENT KBB H-ADJ', 'campaign_name' => 'PARENT KBB H-ADJ HEAD'],
            ['parent' => 'PARENT MS ARM', 'campaign_name' => 'PARENT MS ARM'],
            ['parent' => 'PARENT BETA', 'campaign_name' => 'PARENT BETA'],
            ['parent' => 'PARENT BETA', 'campaign_name' => 'PARENT BETA PT'],
            ['parent' => 'PARENT DRUM MIC 7', 'campaign_name' => 'PARENT DRUM MIC 7 HEAD'],
            ['parent' => 'PARENT MS MOB', 'campaign_name' => 'PARENT MS MOB'],
            ['parent' => 'PARENT MS MOB', 'campaign_name' => 'PARENT MS MOB PT'],
            ['parent' => 'PARENT ND-57X', 'campaign_name' => 'PARENT ND-57X'],
            ['parent' => 'PARENT ND-57X', 'campaign_name' => 'PARENT ND-57X PT'],
            ['parent' => 'PARENT A-55', 'campaign_name' => 'PARENT A-54 PT'],
            ['parent' => 'PARENT WST 04', 'campaign_name' => 'PARENT WST 04 PT'],
            ['parent' => 'PARENT WM', 'campaign_name' => 'PARENT WM 1001 PT'],
            ['parent' => 'PARENT MEGA WP', 'campaign_name' => 'PARENT MEGA WP PT'],
            ['parent' => 'PARENT PARTY SPK', 'campaign_name' => 'PARENT PARTY SPK PT'],
            ['parent' => 'PARENT WST 04', 'campaign_name' => 'PARENT WST 04'],
            ['parent' => 'PARENT PARTY SPK', 'campaign_name' => 'PARENT PARTY SPK'],
            ['parent' => 'PARENT MEGA WP', 'campaign_name' => 'PARENT MEGA WP'],
            ['parent' => 'PARENT WF 672', 'campaign_name' => 'PARENT WF 672'],
            ['parent' => 'PARENT WF 672', 'campaign_name' => 'PARENT WF 672 PT'],
            ['parent' => 'PARENT MEGA KIDS', 'campaign_name' => 'PARENT MEGA KIDS PT'],
            ['parent' => 'PARENT SS HD 3FT', 'campaign_name' => 'PARENT SS HD 3FT HEAD'],
            ['parent' => 'PARENT KS 2X+2T', 'campaign_name' => 'PARENT KS 2X+2T'],
            ['parent' => 'PARENT KS 2X+2T', 'campaign_name' => 'PARENT KS 2X+2T PT'],
            ['parent' => 'PARENT CAR SPEAKER 70', 'campaign_name' => 'PARENT CAR SPEAKER 69 PT'],
            ['parent' => 'PARENT BT 13', 'campaign_name' => 'PARENT BT 13'],
            ['parent' => 'PARENT BT 13', 'campaign_name' => 'PARENT BT 13 PT'],
            ['parent' => 'MS MINI TRI BLK', 'campaign_name' => 'MS MINI TRI BLK FBA'],
            ['parent' => 'PARENT PNB 480 BR', 'campaign_name' => 'PARENT PNB 480 BR'],
            ['parent' => 'PARENT PNB 480 BR', 'campaign_name' => 'PARENT PNB 480 BR PT'],
            ['parent' => 'Parent EDA', 'campaign_name' => 'Parent EDA'],
            ['parent' => 'PARENT Drum Foot Pedal 04', 'campaign_name' => 'PARENT Drum Foot Pedal 04'],
            ['parent' => 'LS 100', 'campaign_name' => 'LS 100'],
            ['parent' => 'LS 100', 'campaign_name' => 'LS 100 PT'],
            ['parent' => 'PARENT 12 SP', 'campaign_name' => 'PARENT 12 SP'],
            ['parent' => 'PARENT 8 WF PP', 'campaign_name' => 'PARENT 8 WF PP'],
            ['parent' => 'PARENT 6.5 WF PP', 'campaign_name' => 'PARENT 6.5 WF PP'],
            ['parent' => 'PARENT 15 WF PP', 'campaign_name' => 'PARENT 15 WF PP'],
            ['parent' => 'PARENT 12 WF PP', 'campaign_name' => 'PARENT 12 WF PP'],
            ['parent' => 'PARENT 10 WF PP', 'campaign_name' => 'PARENT 10 WF PP'],
            ['parent' => 'PARENT MS 080 2PK', 'campaign_name' => 'PARENT MS 080 2PK'],
            ['parent' => 'Parent EDA', 'campaign_name' => 'Parent EDA PT'],
            ['parent' => 'PARENT Guitar Amp Stand', 'campaign_name' => 'PARENT Guitar Amp Stand PT'],
            ['parent' => 'PARENT Guitar Amp Stand', 'campaign_name' => 'PARENT Guitar Amp Stand'],
            ['parent' => 'MX 4CH', 'campaign_name' => 'MX 4CH'],
            ['parent' => 'PARENT MX 4CH', 'campaign_name' => 'PARENT MX 4CH PT'],
            ['parent' => 'PARENT MS 080 2PK', 'campaign_name' => 'PARENT MS 080 2PK PT'],
            ['parent' => 'PARENT DT', 'campaign_name' => 'PARENT DT PT'],
            ['parent' => 'PARENT Drum Foot Pedal 04', 'campaign_name' => 'PARENT Drum Foot Pedal 04 PT'],
            ['parent' => 'PARENT PNB', 'campaign_name' => 'PARENT PNB PT'],
        ];

        foreach ($data as $entry) {
            DB::table('campaign_entries')->insert([
                'parent' => $entry['parent'],
                'campaign_name' => $entry['campaign_name'],
                'created_at' => '2025-08-07 03:25:00',
                'updated_at' => '2025-08-07 03:25:00',
            ]);
        }
    }
}